# pull node image
FROM node:22.12.0-alpine

WORKDIR /app

# Download specific Tailwind CLI for Linux
RUN wget https://github.com/tailwindlabs/tailwindcss/releases/download/v3.4.1/tailwindcss-linux-x64 -O /usr/local/bin/tailwindcss && chmod +x /usr/local/bin/tailwindcss

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install


# Copy the all files from host cwd to container cwd 
COPY . . 

EXPOSE 5173