# Stage 1: Build the app
FROM node:22.12.0-alpine 

# Create app directory
WORKDIR /app 

# Download Tailwind cli
RUN wget https://github.com/tailwindlabs/tailwindcss/releases/download/v3.4.1/tailwindcss-linux-x64 -O /usr/local/bin/tailwindcss && chmod +x /usr/local/bin/tailwindcss

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install


# Copy the all files from host cwd to container cwd 
COPY . . 