# STAGE 1 : build the frontend and backend

FROM node:22.12.0-alpine AS builder

# get Tailwind binary
RUN wget https://github.com/tailwindlabs/tailwindcss/releases/download/v3.4.1/tailwindcss-linux-x64 -O /usr/local/bin/tailwindcss && \
    chmod +x /usr/local/bin/tailwindcss

# Install dependency  (inlucding dev for build)
WORKDIR /app/frontend
COPY frontend/package*.json ./
RUN npm ci

# for server only production dependencies (no build step)
WORKDIR /app/server
COPY server/package*.json ./
RUN npm ci --only=production


#copy the root code
WORKDIR /app
COPY . .


#setup the env files
RUN node setup.js

#build the frontend
WORKDIR /app/frontend
RUN npm run build

# Compile Tailwind :

# Compile the EJS template CSS
WORKDIR /app/server
RUN tailwindcss -i ./public/css/input.css -o ./public/css/output.css --minify



#Compile the frontend tailwind css
WORKDIR /app/frontend
RUN tailwindcss -i ./src/index.css -o ./src/assets/css/output.css --minify




# STAGE 2: The Final Runner (Production Image)
FROM node:22.12.0-alpine AS runner
WORKDIR /app


#  Copy Backend node modules  (cached seperatly)
COPY --from=builder /app/server/node_modules ./node_modules


#  Copy Backend  envs (ignored by dockerignore)
COPY --from=builder /app/server ./.env* 

# copy server source code 
COPY --from=builder /app/server ./

#  Copy Frontend Build 
COPY --from=builder /app/frontend/dist ./dist

# Expose the API port
EXPOSE 3000

# Start the server in prod
CMD ["sh", "-c", "npm run migrate && npm run prod:start"]
