services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./server:/app 
      - /app/node_modules
    command: >
      sh -c "
      npm run migrate && 
      tailwindcss -i ./public/css/input.css -o ./public/css/output.css --watch & 
      node --inspect=0.0.0.0:9229 server.js
      "
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: > #force vite server to listen on all interfaces using --host flag
      sh -c "
      tailwindcss -i ./src/index.css -o ./src/assets/css/output.css &&
      tailwindcss -i ./src/index.css -o ./src/assets/css/output.css --watch & 
      npm run dev -- --host 
      "