# pull node image
FROM node:22.12.0-alpine

WORKDIR /app

# Download specific Tailwind CLI for Linux
RUN wget https://github.com/tailwindlabs/tailwindcss/releases/download/v3.4.1/tailwindcss-linux-x64 -O /usr/local/bin/tailwindcss && chmod +x /usr/local/bin/tailwindcss

# Copy package files and install dependencies
COPY package*.json ./
RUN npm ci

# Copy source
COPY . .

# Expose port
EXPOSE 3000

# Expose the debugger port
EXPOSE 9229